{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-GB",
    "dataSources": [
      {
        "name": "Warehouse",
        "connectionString": "Provider=SQLNCLI11;Integrated Security=SSPI;Persist Security Info=False;User ID=;Initial Catalog=Warehouse;Data Source=z-azd1-sql-001;Initial File Name=;Server SPN=",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Advertiser",
        "columns": [
          {
            "name": "AdvertiserKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AdvertiserKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Advertiser",
            "dataType": "string",
            "sourceColumn": "Advertiser",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Industry",
            "dataType": "string",
            "sourceColumn": "Industry",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Advertiser Group",
            "dataType": "string",
            "sourceColumn": "Advertiser Group"
          },
          {
            "name": "Account Team",
            "dataType": "string",
            "sourceColumn": "Account Team"
          },
          {
            "name": "Business Unit",
            "dataType": "string",
            "sourceColumn": "Business Unit"
          },
          {
            "name": "Agency",
            "dataType": "string",
            "sourceColumn": "Agency"
          },
          {
            "name": "Sub Industry",
            "dataType": "string",
            "sourceColumn": "Sub Industry"
          },
          {
            "name": "Account Manager",
            "dataType": "string",
            "sourceColumn": "Account Manager"
          },
          {
            "name": "Advertiser Logo",
            "dataType": "string",
            "sourceColumn": "Advertiser Logo",
            "dataCategory": "ImageUrl",
            "isDefaultLabel": true
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "dataCategory": "Country"
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent",
            "dataCategory": "Continent"
          },
          {
            "name": "Region Flag",
            "dataType": "string",
            "sourceColumn": "Region Flag",
            "dataCategory": "ImageUrl"
          },
          {
            "name": "Approval Rate",
            "dataType": "double",
            "sourceColumn": "Approval Rate"
          },
          {
            "name": "Advertiser ID",
            "dataType": "int64",
            "sourceColumn": "Advertiser ID",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Advertiser",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[Advertisers].[AdvertiserKey],[ssas].[Advertisers].[Advertiser ID],[ssas].[Advertisers].[Business Unit],[ssas].[Advertisers].[Account Team],[ssas].[Advertisers].[Advertiser Group],[ssas].[Advertisers].[Advertiser],[ssas].[Advertisers].[Industry],[ssas].[Advertisers].[Sub Industry],[ssas].[Advertisers].[Agency],[ssas].[Advertisers].[Account Manager],[ssas].[Advertisers].[Advertiser Logo],[ssas].[Advertisers].[Approval Rate],[ssas].[Advertisers].[Region],[ssas].[Advertisers].[Continent],[ssas].[Advertisers].[Region Flag] FROM [ssas].[Advertisers] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdvertiserKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>98</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Advertiser Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>177</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Advertiser</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>80</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Industry</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Account Team</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>231</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Business Unit</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>93</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Agency</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>66</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Advertiser ID</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>94</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sub Industry</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>92</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Account Manager</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>114</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Advertiser Logo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>106</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Region</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>63</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Continent</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>77</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Region Flag</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Approval Rate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>99</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PreferredTimezone</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>121</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdvertiserKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Advertiser Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Advertiser</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Industry</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Account Team</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Business Unit</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Agency</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Advertiser ID</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sub Industry</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Account Manager</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Advertiser Logo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Region</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Continent</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Region Flag</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Approval Rate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PreferredTimezone</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Advertiser Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Account Team</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Business Unit</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Agency</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Advertiser ID</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sub Industry</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Account Manager</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Advertiser Logo</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Region</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Continent</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Region Flag</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Approval Rate</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PreferredTimezone</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Advertisers",
            "expression": "CALCULATE(DISTINCTCOUNT(Transactions[AdvertiserKey]))",
            "formatString": "#,0"
          },
          {
            "name": "Advertiser Rank",
            "expression": "RANKX( ALL(Advertiser[Advertiser]), [Order Value])",
            "isHidden": true
          },
          {
            "name": "Estimate",
            "expression": " MAX([Approval Rate])",
            "formatString": "0.00",
            "isHidden": true
          }
        ],
        "hierarchies": [
          {
            "name": "Advertisers",
            "levels": [
              {
                "name": "Advertiser Group",
                "ordinal": 0,
                "column": "Advertiser Group"
              },
              {
                "name": "Advertiser",
                "ordinal": 1,
                "column": "Advertiser"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[Advertisers].[AdvertiserKey],[ssas].[Advertisers].[Advertiser ID],[ssas].[Advertisers].[Business Unit],[ssas].[Advertisers].[Account Team],[ssas].[Advertisers].[Advertiser Group],[ssas].[Advertisers].[Advertiser],[ssas].[Advertisers].[Industry],[ssas].[Advertisers].[Sub Industry],[ssas].[Advertisers].[Agency],[ssas].[Advertisers].[Account Manager],[ssas].[Advertisers].[Advertiser Logo],[ssas].[Advertisers].[Approval Rate],[ssas].[Advertisers].[Region],[ssas].[Advertisers].[Continent],[ssas].[Advertisers].[Region Flag] FROM [ssas].[Advertisers] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Advertisers"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>AdvertiserKey</string>",
              "      </key>",
              "      <value>",
              "        <int>98</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Advertiser Group</string>",
              "      </key>",
              "      <value>",
              "        <int>177</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Advertiser</string>",
              "      </key>",
              "      <value>",
              "        <int>80</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Industry</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Account Team</string>",
              "      </key>",
              "      <value>",
              "        <int>231</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Business Unit</string>",
              "      </key>",
              "      <value>",
              "        <int>93</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Agency</string>",
              "      </key>",
              "      <value>",
              "        <int>66</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Advertiser ID</string>",
              "      </key>",
              "      <value>",
              "        <int>94</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sub Industry</string>",
              "      </key>",
              "      <value>",
              "        <int>92</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Account Manager</string>",
              "      </key>",
              "      <value>",
              "        <int>114</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Advertiser Logo</string>",
              "      </key>",
              "      <value>",
              "        <int>106</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Region</string>",
              "      </key>",
              "      <value>",
              "        <int>63</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Continent</string>",
              "      </key>",
              "      <value>",
              "        <int>77</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Region Flag</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Approval Rate</string>",
              "      </key>",
              "      <value>",
              "        <int>99</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PreferredTimezone</string>",
              "      </key>",
              "      <value>",
              "        <int>121</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>AdvertiserKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Advertiser Group</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Advertiser</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Industry</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Account Team</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Business Unit</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Agency</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Advertiser ID</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sub Industry</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Account Manager</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Advertiser Logo</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Region</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Continent</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Region Flag</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Approval Rate</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PreferredTimezone</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Advertiser Group</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Account Team</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Business Unit</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Agency</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Advertiser ID</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sub Industry</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Account Manager</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Advertiser Logo</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Region</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Continent</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Region Flag</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Approval Rate</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PreferredTimezone</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Calendar",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "CalendarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CalendarMonthNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarMonthNumber",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "Short Date",
            "sourceProviderType": "DBDate",
            "tableDetailPosition": 4,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year",
            "sourceProviderType": "WChar",
            "tableDetailPosition": 0
          },
          {
            "name": "Half",
            "dataType": "string",
            "sourceColumn": "Half",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "sortByColumn": "YearQuarterNumber",
            "sourceProviderType": "WChar",
            "tableDetailPosition": 1
          },
          {
            "name": "YearNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "YearNumber",
            "formatString": "0"
          },
          {
            "name": "DaysInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DaysInYear"
          },
          {
            "name": "DaysInQuarter",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DaysInQuarter"
          },
          {
            "name": "DaysInMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DaysInMonth"
          },
          {
            "name": "QuarterInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "QuarterInYear"
          },
          {
            "name": "MonthInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthInYear"
          },
          {
            "name": "DayInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DayInYear"
          },
          {
            "name": "DayInMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DayInMonth"
          },
          {
            "name": "MonthInEpoch",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthInEpoch"
          },
          {
            "name": "YearInEpoch",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "YearInEpoch"
          },
          {
            "name": "QuarterInEpoch",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "QuarterInEpoch"
          },
          {
            "name": "DayInEpoch",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DayInEpoch"
          },
          {
            "name": "YearDayNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "YearDayNumber"
          },
          {
            "name": "QuarterDayNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "QuarterDayNumber"
          },
          {
            "name": "MonthDayNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthDayNumber"
          },
          {
            "name": "QuarterDays",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "QuarterDays"
          },
          {
            "name": "MonthDays",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthDays"
          },
          {
            "name": "YearQuarterNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "YearQuarterNumber"
          },
          {
            "name": "YearMonthNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "YearMonthNumber"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "sortByColumn": "CalendarMonthNumber",
            "tableDetailPosition": 2
          },
          {
            "name": "ISO Year",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ISO Year"
          },
          {
            "name": "ISO Week",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ISO Week"
          },
          {
            "name": "Day Type",
            "dataType": "string",
            "sourceColumn": "Day Type"
          },
          {
            "name": "WeekInEpoch",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "WeekInEpoch"
          },
          {
            "name": "ISOYearNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ISOYearNumber"
          },
          {
            "name": "ISOWeekNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ISOWeekNumber"
          },
          {
            "name": "DayOfWeek",
            "dataType": "string",
            "sourceColumn": "DayOfWeek",
            "sortByColumn": "DayOfWeekNumber"
          },
          {
            "name": "DayOfWeekNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DayOfWeekNumber"
          },
          {
            "name": "Event",
            "dataType": "string",
            "sourceColumn": "Event"
          }
        ],
        "partitions": [
          {
            "name": "Calendar",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[Calendar].* FROM [ssas].[Calendar] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarMonthNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>140</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>89</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>53</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>52</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Half</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>49</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Quarter</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>68</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>99</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>88</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DaysInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DaysInQuarter</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>102</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DaysInMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>94</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>100</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>92</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>81</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>89</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearDayNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>108</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterDayNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>124</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthDayNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>116</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterDays</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>92</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthDays</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>84</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearQuarterNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>127</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearMonthNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Month</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>60</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISO Week</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>109</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISO Year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>103</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Day Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>106</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISOYearNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>WeekInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>96</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISOWeekNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>112</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayOfWeek</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>88</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayOfWeekNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>125</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Event</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>58</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarMonthNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Half</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Quarter</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DaysInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DaysInQuarter</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DaysInMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearDayNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterDayNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthDayNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterDays</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthDays</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearQuarterNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearMonthNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Month</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISO Week</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>27</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISO Year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Day Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>28</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISOYearNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>30</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>WeekInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>29</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISOWeekNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>31</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayOfWeek</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>32</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayOfWeekNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>33</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Event</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>34</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DaysInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DaysInQuarter</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DaysInMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearDayNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterDayNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthDayNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterDays</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthDays</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearQuarterNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearMonthNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Month</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISO Week</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISO Year</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Day Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISOYearNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>WeekInEpoch</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ISOWeekNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayOfWeek</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayOfWeekNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Event</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "YQM",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              }
            ]
          },
          {
            "name": "YW",
            "levels": [
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date"
              },
              {
                "name": "ISO Year",
                "ordinal": 0,
                "column": "ISO Year"
              },
              {
                "name": "ISO Week",
                "ordinal": 1,
                "column": "ISO Week"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[Calendar].* FROM [ssas].[Calendar] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Calendar"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>CalendarKey</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CalendarMonthNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>140</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>89</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Date</string>",
              "      </key>",
              "      <value>",
              "        <int>53</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Year</string>",
              "      </key>",
              "      <value>",
              "        <int>52</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Half</string>",
              "      </key>",
              "      <value>",
              "        <int>49</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Quarter</string>",
              "      </key>",
              "      <value>",
              "        <int>68</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <int>107</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <int>99</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <int>88</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DaysInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DaysInQuarter</string>",
              "      </key>",
              "      <value>",
              "        <int>102</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DaysInMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>94</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>100</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>92</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>81</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>89</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearDayNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>108</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterDayNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>124</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthDayNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>116</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterDays</string>",
              "      </key>",
              "      <value>",
              "        <int>92</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthDays</string>",
              "      </key>",
              "      <value>",
              "        <int>84</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearQuarterNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>127</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearMonthNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Month</string>",
              "      </key>",
              "      <value>",
              "        <int>60</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISO Week</string>",
              "      </key>",
              "      <value>",
              "        <int>109</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISO Year</string>",
              "      </key>",
              "      <value>",
              "        <int>103</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Day Type</string>",
              "      </key>",
              "      <value>",
              "        <int>106</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISOYearNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>107</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>WeekInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <int>96</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISOWeekNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>112</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayOfWeek</string>",
              "      </key>",
              "      <value>",
              "        <int>88</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayOfWeekNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>125</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Event</string>",
              "      </key>",
              "      <value>",
              "        <int>58</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>CalendarKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CalendarMonthNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Date</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Year</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Half</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Quarter</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DaysInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DaysInQuarter</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DaysInMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearDayNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterDayNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthDayNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterDays</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthDays</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearQuarterNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearMonthNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Month</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISO Week</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISO Year</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Day Type</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISOYearNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>30</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>WeekInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <int>29</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISOWeekNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>31</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayOfWeek</string>",
              "      </key>",
              "      <value>",
              "        <int>32</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayOfWeekNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>33</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Event</string>",
              "      </key>",
              "      <value>",
              "        <int>34</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>YearNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DaysInYear</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DaysInQuarter</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DaysInMonth</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterInYear</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthInYear</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInYear</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInMonth</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearDayNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterDayNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthDayNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterDays</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthDays</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearQuarterNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearMonthNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Month</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISO Week</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISO Year</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Day Type</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISOYearNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>WeekInEpoch</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ISOWeekNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayOfWeek</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayOfWeekNumber</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Event</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Clicks",
        "columns": [
          {
            "name": "CalendarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "AdvertiserKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AdvertiserKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "PublisherKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PublisherKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ClickCount",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ClickCount",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DeviceKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DeviceKey"
          },
          {
            "name": "SourceSystemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SourceSystemKey"
          }
        ],
        "partitions": [
          {
            "name": "ClicksByDate",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[Clicks].* FROM [ssas].[Clicks] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdvertiserKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>98</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PublisherKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ClickCount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>80</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>80</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SourceSystemKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>116</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdvertiserKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PublisherKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ClickCount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SourceSystemKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>DeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SourceSystemKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Clicks",
            "expression": "SUM([ClickCount])",
            "formatString": "#,0",
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks PY",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "\t\t// Full month selected.",
              "        CALCULATE (",
              "            [Clicks],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        ),",
              "\t\t// Partial month selected.",
              "        CALCULATE (",
              "            [Clicks],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks PQ",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected.",
              "        CALCULATE (",
              "            [Clicks],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Clicks],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks PM",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected. ",
              "        CALCULATE (",
              "            [Clicks],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Clicks],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [Clicks PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [Clicks PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Clicks PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Clicks PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Clicks PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks PW",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[WeekInEpoch] ),",
              "    CALCULATE (",
              "        [Clicks],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[WeekInEpoch] ),",
              "            'Calendar'[WeekInEpoch]",
              "                = EARLIER ( 'Calendar'[WeekInEpoch] ) - 1",
              "        )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks PD",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[DayInEpoch] ),",
              "    CALCULATE (",
              "        [Clicks],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[DayInEpoch] ),",
              "            'Calendar'[DayInEpoch]",
              "                = EARLIER ( 'Calendar'[DayInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks POP",
            "expression": "[Clicks] - [Clicks PP]",
            "formatString": "#,0",
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks POP%",
            "expression": "DIVIDE([Clicks POP],[Clicks PP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks PPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [Clicks],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks PPQ",
            "expression": [
              "",
              "CALCULATE (",
              "    [Clicks],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks PPM",
            "expression": [
              "",
              "CALCULATE (",
              "    [Clicks],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks PPW",
            "expression": [
              "",
              "CALCULATE (",
              "    [Clicks],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks PPD",
            "expression": "0",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks SPLY",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [Clicks PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Clicks PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Clicks PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Clicks PPW],",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks YOY",
            "expression": " [Clicks] - [Clicks PY]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks QOQ",
            "expression": " [Clicks] - [Clicks PQ]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks MOM",
            "expression": " [Clicks] - [Clicks PM]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks WOW",
            "expression": " [Clicks] - [Clicks PW]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks YOY%",
            "expression": " DIVIDE ( [Clicks YOY], [Clicks PY] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks QOQ%",
            "expression": " DIVIDE ( [Clicks QOQ], [Clicks PQ] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks MOM%",
            "expression": " DIVIDE ( [Clicks MOM], [Clicks PM] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks WOW%",
            "expression": " DIVIDE ( [Clicks WOW], [Clicks PW] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "EPC (Advertiser)",
            "description": "Earnings per Click (Advertiser)",
            "expression": " DIVIDE(Transactions[Order Value], Clicks[Clicks])",
            "formatString": "0.00",
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Publisher)",
            "description": "Earnings per Click (Publisher)",
            "expression": " DIVIDE(Transactions[Commission], Clicks[Clicks])",
            "formatString": "0.00",
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Advertiser) PD",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[DayInEpoch] ),",
              "    CALCULATE (",
              "        [EPC (Advertiser)],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[DayInEpoch] ),",
              "            'Calendar'[DayInEpoch]",
              "                = EARLIER ( 'Calendar'[DayInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Publisher) PD",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[DayInEpoch] ),",
              "    CALCULATE (",
              "        [EPC (Publisher)],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[DayInEpoch] ),",
              "            'Calendar'[DayInEpoch]",
              "                = EARLIER ( 'Calendar'[DayInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) PW",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[WeekInEpoch] ),",
              "    CALCULATE (",
              "        [EPC (Publisher)],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[WeekInEpoch] ),",
              "            'Calendar'[WeekInEpoch]",
              "                = EARLIER ( 'Calendar'[WeekInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Advertiser) PW",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[WeekInEpoch] ),",
              "    CALCULATE (",
              "        [EPC (Advertiser)],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[WeekInEpoch] ),",
              "            'Calendar'[WeekInEpoch]",
              "                = EARLIER ( 'Calendar'[WeekInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) PM",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected. ",
              "        CALCULATE (",
              "            [EPC (Advertiser)],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [EPC (Advertiser)],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Publisher) PM",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected. ",
              "        CALCULATE (",
              "            [EPC (Publisher)],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [EPC (Publisher)],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Advertiser) PQ",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected.",
              "        CALCULATE (",
              "            [EPC (Advertiser)],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [EPC (Advertiser)],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Publisher) PQ",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected.",
              "        CALCULATE (",
              "            [EPC (Publisher)],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [EPC (Publisher)],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) PY",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "\t\t// Full month selected.",
              "        CALCULATE (",
              "            [EPC (Publisher)],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        ),",
              "\t\t// Partial month selected.",
              "        CALCULATE (",
              "            [EPC (Publisher)],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Advertiser) PY",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "\t\t// Full month selected.",
              "        CALCULATE (",
              "            [EPC (Advertiser)],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        ),",
              "\t\t// Partial month selected.",
              "        CALCULATE (",
              "            [EPC (Advertiser)],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Publisher) PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [EPC (Publisher) PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [EPC (Publisher) PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [EPC (Publisher) PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [EPC (Publisher) PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [EPC (Publisher) PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Advertiser) PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [EPC (Advertiser) PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [EPC (Advertiser) PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [EPC (Advertiser) PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [EPC (Advertiser) PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [EPC (Advertiser) PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) POP",
            "expression": "[EPC (Advertiser)] - [EPC (Advertiser) PP]",
            "formatString": "0.00",
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Publisher) POP",
            "expression": "[EPC (Publisher)] - [EPC (Publisher) PP]",
            "formatString": "0.00",
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Advertiser) POP%",
            "expression": "DIVIDE([EPC (Advertiser) POP],[EPC (Advertiser) PP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Publisher) POP%",
            "expression": "DIVIDE([EPC (Publisher) POP],[EPC (Publisher) PP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Advertiser) DOD",
            "expression": " [EPC (Advertiser)] - [EPC (Advertiser) PD]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) DOD%",
            "expression": " DIVIDE ( [EPC (Advertiser) DOD], [EPC (Advertiser) PD] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) WOW",
            "expression": " [EPC (Advertiser)] - [EPC (Advertiser) PW]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) MOM",
            "expression": " [EPC (Advertiser)] - [EPC (Advertiser) PM]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) QOQ",
            "expression": " [EPC (Advertiser)] - [EPC (Advertiser) PQ]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) YOY",
            "expression": " [EPC (Advertiser)] - [EPC (Advertiser) PY]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) WOW%",
            "expression": " DIVIDE ( [EPC (Advertiser) WOW], [EPC (Advertiser) PW] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) MOM%",
            "expression": " DIVIDE ( [EPC (Advertiser) MOM], [EPC (Advertiser) PM] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) QOQ%",
            "expression": " DIVIDE ( [EPC (Advertiser) QOQ], [EPC (Advertiser) PQ] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) YOY%",
            "expression": " DIVIDE ( [EPC (Advertiser) YOY], [EPC (Advertiser) PY] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Publisher) DOD",
            "expression": " [EPC (Publisher)] - [EPC (Publisher) PD]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) DOD%",
            "expression": " DIVIDE ( [EPC (Publisher) DOD], [EPC (Publisher) PD] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) WOW",
            "expression": " [EPC (Publisher)] - [EPC (Publisher) PW]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) WOW%",
            "expression": " DIVIDE ( [EPC (Publisher) WOW], [EPC (Publisher) PW] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) MOM",
            "expression": " [EPC (Publisher)] - [EPC (Publisher) PM]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) MOM%",
            "expression": " DIVIDE ( [EPC (Publisher) MOM], [EPC (Publisher) PM] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) QOQ",
            "expression": " [EPC (Publisher)] - [EPC (Publisher) PQ]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) QOQ%",
            "expression": " DIVIDE ( [EPC (Publisher) QOQ], [EPC (Publisher) PQ] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) YOY",
            "expression": " [EPC (Publisher)] - [EPC (Publisher) PY]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) YOY%",
            "expression": " DIVIDE ( [EPC (Publisher) YOY], [EPC (Publisher) PY] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "Clicks DOD",
            "expression": " [Clicks] - [Clicks PD]",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "Clicks DOD%",
            "expression": " DIVIDE ( [Clicks DOD], [Clicks PD] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Metrics"
          },
          {
            "name": "EPC (Advertiser) PPD",
            "expression": " 0",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) PPW",
            "expression": [
              "",
              "CALCULATE (",
              "    [EPC (Advertiser)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) PPM",
            "expression": [
              "",
              "CALCULATE (",
              "    [EPC (Advertiser)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) PPQ",
            "expression": [
              "",
              "CALCULATE (",
              "    [EPC (Advertiser)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) PPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [EPC (Advertiser)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Advertiser) SPLY",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [EPC (Advertiser) PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [EPC (Advertiser) PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [EPC (Advertiser) PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [EPC (Advertiser) PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Earnings per Click (Advertiser)"
          },
          {
            "name": "EPC (Publisher) PPD",
            "expression": " 0",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) PPW",
            "expression": [
              "",
              "CALCULATE (",
              "    [EPC (Publisher)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) PPM",
            "expression": [
              "",
              "CALCULATE (",
              "    [EPC (Publisher)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) PPQ",
            "expression": [
              "",
              "CALCULATE (",
              "    [EPC (Publisher)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) PPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [EPC (Publisher)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Earnings per Click (Publisher)"
          },
          {
            "name": "EPC (Publisher) SPLY",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [EPC (Publisher) PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [EPC (Publisher) PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [EPC (Publisher) PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [EPC (Publisher) PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Earnings per Click (Publisher)"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[Clicks].* FROM [ssas].[Clicks] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Clicks"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>CalendarKey</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdvertiserKey</string>",
              "      </key>",
              "      <value>",
              "        <int>98</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PublisherKey</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ClickCount</string>",
              "      </key>",
              "      <value>",
              "        <int>80</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <int>80</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SourceSystemKey</string>",
              "      </key>",
              "      <value>",
              "        <int>116</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>CalendarKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdvertiserKey</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PublisherKey</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ClickCount</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SourceSystemKey</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>DeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SourceSystemKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Publisher",
        "columns": [
          {
            "name": "PublisherKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PublisherKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Publisher",
            "dataType": "string",
            "sourceColumn": "Publisher",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Publisher Vertical",
            "dataType": "string",
            "sourceColumn": "Publisher Vertical"
          },
          {
            "name": "Publisher Type",
            "dataType": "string",
            "sourceColumn": "Publisher Type"
          },
          {
            "name": "Publisher Group",
            "dataType": "string",
            "sourceColumn": "Publisher Group"
          },
          {
            "name": "Publisher Logo",
            "dataType": "string",
            "sourceColumn": "Publisher Logo",
            "dataCategory": "ImageUrl",
            "isDefaultLabel": true
          },
          {
            "name": "Publisher Type Group",
            "dataType": "string",
            "sourceColumn": "Publisher Type Group"
          },
          {
            "name": "Blacklist Status",
            "dataType": "string",
            "sourceColumn": "Blacklist Status"
          },
          {
            "name": "Publisher ID",
            "dataType": "int64",
            "sourceColumn": "Publisher ID",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Publisher Website",
            "dataType": "string",
            "sourceColumn": "Publisher Website",
            "dataCategory": "WebUrl"
          }
        ],
        "partitions": [
          {
            "name": "Publisher",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[Publishers].* FROM [ssas].[Publishers] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>PublisherKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>139</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>100</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Vertical</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>111</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher ID</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>87</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Logo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>99</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Type Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>193</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Blacklist Status</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Website</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>115</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>PublisherKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Vertical</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher ID</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Logo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Type Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Blacklist Status</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Website</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Vertical</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher ID</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Logo</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Type Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Blacklist Status</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Publisher Website</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Publishers",
            "expression": "CALCULATE(DISTINCTCOUNT(Transactions[PublisherKey]))",
            "formatString": "#,0"
          },
          {
            "name": "Publisher Rank",
            "expression": "RANKX( ALL(Publisher[Publisher]), [Order Value])",
            "isHidden": true
          },
          {
            "name": "First Sale",
            "expression": "FIRSTDATE('Calendar'[Date])",
            "formatString": "General Date",
            "isHidden": true
          },
          {
            "name": "Publishers PD",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[DayInEpoch] ),",
              "    CALCULATE (",
              "        [Publishers],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[DayInEpoch] ),",
              "            'Calendar'[DayInEpoch]",
              "                = EARLIER ( 'Calendar'[DayInEpoch] ) - 1",
              "        )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Publishers PW",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[WeekInEpoch] ),",
              "    CALCULATE (",
              "        [Publishers],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[WeekInEpoch] ),",
              "            'Calendar'[WeekInEpoch]",
              "                = EARLIER ( 'Calendar'[WeekInEpoch] ) - 1",
              "        )",
              "    )",
              ")",
              ""
            ],
            "isHidden": true
          },
          {
            "name": "Publishers PM",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected. ",
              "        CALCULATE (",
              "            [Publishers],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Publishers],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "isHidden": true
          },
          {
            "name": "Publishers PQ",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected.",
              "        CALCULATE (",
              "            [Publishers],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Publishers],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "isHidden": true
          },
          {
            "name": "Publishers PY",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "\t\t// Full month selected.",
              "        CALCULATE (",
              "            [Publishers],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        ),",
              "\t\t// Partial month selected.",
              "        CALCULATE (",
              "            [Publishers],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "isHidden": true
          },
          {
            "name": "Publishers PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [Publishers PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [Publishers PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Publishers PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Publishers PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Publishers PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Publishers POP",
            "expression": "[Publishers] - [Publishers PP]",
            "formatString": "#,0"
          },
          {
            "name": "Publishers POP%",
            "expression": "DIVIDE([Publishers POP],[Publishers PP])",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%"
          },
          {
            "name": "Publishers DOD",
            "expression": " [Publishers] - [Publishers PD]",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Publishers DOD%",
            "expression": " DIVIDE ( [Publishers DOD], [Publishers PD] )",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true
          },
          {
            "name": "Publishers WOW",
            "expression": " [Publishers] - [Publishers PW]",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Publishers WOW%",
            "expression": " DIVIDE ( [Publishers WOW], [Publishers PW] )",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true
          },
          {
            "name": "Publishers MOM",
            "expression": " [Publishers] - [Publishers PM]",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Publishers MOM%",
            "expression": " DIVIDE ( [Publishers MOM], [Publishers PM] )",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true
          },
          {
            "name": "Publishers QOQ",
            "expression": " [Publishers] - [Publishers PQ]",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Publishers QOQ%",
            "expression": " DIVIDE ( [Publishers QOQ], [Publishers PQ] )",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true
          },
          {
            "name": "Publishers YOY",
            "expression": " [Publishers] - [Publishers PY]",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Publishers YOY%",
            "expression": " DIVIDE ( [Publishers YOY], [Publishers PY] )",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true
          },
          {
            "name": "Publishers PPD",
            "expression": "0",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Publishers PPW",
            "expression": [
              "",
              "CALCULATE (",
              "    [Publishers],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Publishers PPM",
            "expression": [
              "",
              "CALCULATE (",
              "    [Publishers],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Publishers PPQ",
            "expression": [
              "",
              "CALCULATE (",
              "    [Publishers],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Publishers PPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [Publishers],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Publishers SPLY",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [Publishers PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Publishers PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Publishers PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Publishers PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[Publishers].* FROM [ssas].[Publishers] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Publishers"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>PublisherKey</string>",
              "      </key>",
              "      <value>",
              "        <int>139</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Type</string>",
              "      </key>",
              "      <value>",
              "        <int>100</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Vertical</string>",
              "      </key>",
              "      <value>",
              "        <int>111</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Group</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher ID</string>",
              "      </key>",
              "      <value>",
              "        <int>87</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Logo</string>",
              "      </key>",
              "      <value>",
              "        <int>99</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Type Group</string>",
              "      </key>",
              "      <value>",
              "        <int>193</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Blacklist Status</string>",
              "      </key>",
              "      <value>",
              "        <int>101</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Website</string>",
              "      </key>",
              "      <value>",
              "        <int>115</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>PublisherKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Type</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Vertical</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Group</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher ID</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Logo</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Type Group</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Blacklist Status</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Website</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Type</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Vertical</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Group</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher ID</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Logo</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Type Group</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Blacklist Status</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Publisher Website</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Flags",
        "columns": [
          {
            "name": "TransactionFlagKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TransactionFlagKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Commission Status",
            "dataType": "string",
            "sourceColumn": "Commission Status",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Transaction Source",
            "dataType": "string",
            "sourceColumn": "Transaction Source"
          },
          {
            "name": "Transaction Type",
            "dataType": "string",
            "sourceColumn": "Transaction Type"
          },
          {
            "name": "Paid Status",
            "dataType": "string",
            "sourceColumn": "Paid Status"
          }
        ],
        "partitions": [
          {
            "name": "TransactionFlags",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[TransactionFlags].* FROM [ssas].[TransactionFlags] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>TransactionFlagKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>124</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Transaction Source</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Transaction Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Commission Status</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Paid Status</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>117</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>TransactionFlagKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Transaction Source</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Transaction Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Commission Status</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Paid Status</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Transaction Source</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Transaction Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Paid Status</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[TransactionFlags].* FROM [ssas].[TransactionFlags] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "TransactionFlags"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>TransactionFlagKey</string>",
              "      </key>",
              "      <value>",
              "        <int>124</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Transaction Source</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Transaction Type</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Commission Status</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Paid Status</string>",
              "      </key>",
              "      <value>",
              "        <int>117</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>TransactionFlagKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Transaction Source</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Transaction Type</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Commission Status</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Paid Status</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Transaction Source</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Transaction Type</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Paid Status</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Transactions",
        "columns": [
          {
            "name": "CalendarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "AdvertiserKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AdvertiserKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "PublisherKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PublisherKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "TransactionFlagKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TransactionFlagKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "TransactionCount",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TransactionCount",
            "sourceProviderType": "Integer"
          },
          {
            "name": "SalesAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesAmount",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "CommissionAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CommissionAmount",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "FeeAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FeeAmount"
          },
          {
            "name": "DeviceKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DeviceKey"
          },
          {
            "type": "calculated",
            "name": "Sales Date",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "RELATED ( 'Calendar'[Date] )",
            "formatString": "yyyy-MM-dd",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"2057\" Group=\"ShortDate\" FormatString=\"yyyy-MM-dd\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "LocationKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LocationKey"
          },
          {
            "name": "InitiatingDeviceKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "InitiatingDeviceKey"
          },
          {
            "name": "SourceSystemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SourceSystemKey"
          }
        ],
        "partitions": [
          {
            "name": "TransactionsByDate",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[Transactions].* FROM [ssas].[Transactions] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdvertiserKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>98</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PublisherKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TransactionFlagKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>124</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TransactionCount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>115</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>92</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CommissionAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FeeAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>80</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>LocationKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>88</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>InitiatingDeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SourceSystemKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>116</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdvertiserKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PublisherKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TransactionFlagKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TransactionCount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CommissionAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FeeAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>LocationKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>InitiatingDeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SourceSystemKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>FeeAmount</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>LocationKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>InitiatingDeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SourceSystemKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "AOV",
            "description": "Average Order Value",
            "expression": "DIVIDE([Order Value], [Sales])",
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "CR",
            "description": "Conversion Rate",
            "expression": "DIVIDE([Sales], [Clicks])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "Sales POP",
            "expression": "[Sales] - [Sales PP]",
            "formatString": "#,0",
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales PPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [Sales],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales PPM",
            "expression": [
              "",
              "CALCULATE (",
              "    [Sales],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales SPLY",
            "description": "Sales for the Same Period Last Year",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [Sales PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Sales PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Sales PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Sales PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales PPQ",
            "expression": [
              "",
              "CALCULATE (",
              "    [Sales],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Commission PPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [Commission],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Commission PPQ",
            "expression": [
              "",
              "CALCULATE (",
              "    [Commission],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Commission PPM",
            "expression": [
              "",
              "CALCULATE (",
              "    [Commission],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Commission SPLY",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [Commission PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Commission PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Commission PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Commission PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Sales POP%",
            "expression": "DIVIDE([Sales POP],[Sales PP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Commission POP%",
            "expression": "DIVIDE([Commission POP],[Commission PP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "GP POP%",
            "expression": "DIVIDE([GP POP],[GP PP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP PPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [GP],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP PPQ",
            "expression": [
              "",
              "CALCULATE (",
              "    [GP],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP PPM",
            "expression": [
              "",
              "CALCULATE (",
              "    [GP],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP SPLY",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [GP PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [GP PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [GP PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [GP PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "CTR",
            "expression": " DIVIDE([Clicks], [Impressions])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "Sales PY",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected.",
              "        CALCULATE (",
              "            [Sales],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        ),",
              "        // Partial month selected.",
              "        CALCULATE (",
              "            [Sales],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales PQ",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected.",
              "        CALCULATE (",
              "            [Sales],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Sales],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales PM",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    VAR PreviousYearMonth =",
              "        FILTER (",
              "            ALL ( 'Calendar'[YearMonthNumber] ),",
              "            'Calendar'[YearMonthNumber]",
              "                = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "        )",
              "    RETURN",
              "        IF (",
              "            CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "                = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "            CALCULATE ( [Sales], ALL ( 'Calendar' ), PreviousYearMonth ),",
              "            CALCULATE (",
              "                [Sales],",
              "                ALL ( 'Calendar' ),",
              "                CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "                PreviousYearMonth",
              "            )",
              "        )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales PW",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[WeekInEpoch] ),",
              "    CALCULATE (",
              "        [Sales],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[WeekInEpoch] ),",
              "            'Calendar'[WeekInEpoch]",
              "                = EARLIER ( 'Calendar'[WeekInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [Sales PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [Sales PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Sales PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Sales PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Sales PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales YOY",
            "expression": "[Sales] - [Sales PY]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales QOQ",
            "expression": "[Sales] - [Sales PQ]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales MOM",
            "expression": "[Sales] - [Sales PM]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales WOW",
            "expression": " [Sales] - [Sales PW]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales YOY%",
            "expression": "DIVIDE ( [Sales YOY], [Sales PY] )",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales QOQ%",
            "expression": "DIVIDE ( [Sales QOQ], [Sales PQ] )",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales MOM%",
            "expression": "DIVIDE ( [Sales MOM], [Sales PM] )",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales WOW%",
            "expression": "0",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales",
            "expression": "SUM(Transactions[TransactionCount])",
            "formatString": "#,0",
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Commission",
            "description": "Commission",
            "expression": [
              "",
              "ROUND (",
              "    IF (",
              "        HASONEVALUE ( Currencies[Currency Code] ),",
              "        SUMX (",
              "            CROSSJOIN ( Currencies, 'Calendar' ),",
              "            CALCULATE (",
              "                VALUES ( ExchangeRates[ExchangeRate] ) * SUM ( Transactions[CommissionAmount] )",
              "            )",
              "        ),",
              "        SUM ( Transactions[CommissionAmount] )",
              "    ),",
              "    2",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "GP",
            "description": "Gross Profit",
            "expression": [
              "",
              "ROUND (",
              "    IF (",
              "        HASONEVALUE ( Currencies[Currency Code] ),",
              "        SUMX (",
              "            CROSSJOIN ( Currencies, 'Calendar' ),",
              "            CALCULATE (",
              "                VALUES ( ExchangeRates[ExchangeRate] ) * SUM ( Transactions[FeeAmount] )",
              "            )",
              "        ),",
              "        SUM ( Transactions[FeeAmount] )",
              "    ),",
              "    2",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "Commission PY",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "\t\t// Full month selected.",
              "        CALCULATE (",
              "            [Commission],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        ),",
              "\t\t// Partial month selected.",
              "        CALCULATE (",
              "            [Commission],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission PQ",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected.",
              "        CALCULATE (",
              "            [Commission],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Commission],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission PM",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected. ",
              "        CALCULATE (",
              "            [Commission],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Commission],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission PW",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[WeekInEpoch] ),",
              "    CALCULATE (",
              "        [Commission],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[WeekInEpoch] ),",
              "            'Calendar'[WeekInEpoch]",
              "                = EARLIER ( 'Calendar'[WeekInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [Commission PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [Commission PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Commission PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Commission PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Commission PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "GP PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [GP PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [GP PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [GP PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [GP PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [GP PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP PW",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[WeekInEpoch] ),",
              "    CALCULATE (",
              "        [GP],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[WeekInEpoch] ),",
              "            'Calendar'[WeekInEpoch]",
              "                = EARLIER ( 'Calendar'[WeekInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP PY",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "\t\t// Full month selected.",
              "        CALCULATE (",
              "            [GP],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        ),",
              "\t\t// Partial month selected.",
              "        CALCULATE (",
              "            [GP],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP PQ",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected.",
              "        CALCULATE (",
              "            [GP],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [GP],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP PM",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected. ",
              "        CALCULATE (",
              "            [GP],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [GP],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "Commission YOY",
            "expression": "[Commission] - [Commission PY]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission QOQ",
            "expression": "[Commission] - [Commission PQ]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission MOM",
            "expression": "[Commission] - [Commission PM]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission WOW",
            "expression": " [Commission] - [Commission PW]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission YOY%",
            "expression": "DIVIDE ( [Commission YOY], [Commission PY] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission QOQ%",
            "expression": "DIVIDE ( [Commission QOQ], [Commission PQ] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission MOM%",
            "expression": "DIVIDE ( [Commission MOM], [Commission PM] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission WOW%",
            "expression": "0",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "GP YOY",
            "expression": "[GP] - [GP PY]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP QOQ",
            "expression": "[GP] - [GP PQ]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP MOM",
            "expression": "[GP] - [GP PM]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP WOW",
            "expression": " [GP] - [GP PW]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP WOW%",
            "expression": "0",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP YOY%",
            "expression": "DIVIDE ( [GP YOY], [GP PY] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP QOQ%",
            "expression": "DIVIDE ( [GP QOQ], [GP PQ] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP MOM%",
            "expression": "DIVIDE ( [GP MOM], [GP PM] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "Costs PW",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[WeekInEpoch] ),",
              "    CALCULATE (",
              "        [Costs (inc Fee)],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[WeekInEpoch] ),",
              "            'Calendar'[WeekInEpoch]",
              "                = EARLIER ( 'Calendar'[WeekInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "GP POP",
            "expression": "[GP] - [GP PP]",
            "formatString": "#,0.00",
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "Commission POP",
            "expression": "[Commission] - [Commission PP]",
            "formatString": "#,0.00",
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "eCPM",
            "description": "Effective Cost Per Mille (thousand)",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( 'Publisher'[Publisher] ),",
              "        DIVIDE ( Transactions[Commission], Impressions[Impressions] ),",
              "        DIVIDE ( Transactions[Costs (inc Fee)], Impressions[Impressions] )",
              "    )",
              "        * 1000"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Uncategorised Metrics"
          },
          {
            "name": "eCPC",
            "description": "Effective Cost Per Click",
            "expression": [
              "",
              "    IF (",
              "        HASONEVALUE ( 'Publisher'[Publisher] ),",
              "        DIVIDE ( Transactions[Commission], Clicks[Clicks] ),",
              "        DIVIDE ( Transactions[Costs (inc Fee)], Clicks[Clicks] )",
              "    )"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Uncategorised Metrics"
          },
          {
            "name": "eCPS",
            "description": "Estimated Cost Per Sale",
            "expression": [
              "",
              "IF (",
              "    HASONEVALUE ( 'Advertiser'[Advertiser] ),",
              "    DIVIDE ( Transactions[Commission], Advertiser[Estimate] ),",
              "    BLANK()",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "Order Value POP",
            "expression": "[Order Value] - [Order Value PP]",
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value PPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [Order Value],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Order Value PPQ",
            "expression": [
              "",
              "CALCULATE (",
              "    [Order Value],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Order Value PPM",
            "expression": [
              "",
              "CALCULATE (",
              "    [Order Value],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Order Value SPLY",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [Order Value PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Order Value PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Order Value PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Order Value PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value POP%",
            "expression": "DIVIDE([Order Value POP],[Order Value PP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value PY",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "\t\t// Full month selected.",
              "        CALCULATE (",
              "            [Order Value],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        ),",
              "\t\t// Partial month selected.",
              "        CALCULATE (",
              "            [Order Value],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value PQ",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected.",
              "        CALCULATE (",
              "            [Order Value],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Order Value],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value PM",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected. ",
              "        CALCULATE (",
              "            [Order Value],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Order Value],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value PW",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[WeekInEpoch] ),",
              "    CALCULATE (",
              "        [Order Value],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[WeekInEpoch] ),",
              "            'Calendar'[WeekInEpoch]",
              "                = EARLIER ( 'Calendar'[WeekInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [Order Value PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [Order Value PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Order Value PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Order Value PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Order Value PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value YOY",
            "expression": "[Order Value] - [Order Value PY]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value QOQ",
            "expression": "[Order Value] - [Order Value PQ]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value MOM",
            "expression": "[Order Value] - [Order Value PM]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value WOW",
            "expression": " [Order Value] - [Order Value PW]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value YOY%",
            "expression": "DIVIDE ( [Order Value YOY], [Order Value PY] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value QOQ%",
            "expression": "DIVIDE ( [Order Value QOQ], [Order Value PQ] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value MOM%",
            "expression": "DIVIDE ( [Order Value MOM], [Order Value PM] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value WOW%",
            "expression": "0",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Costs PY",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "\t\t// Full month selected.",
              "        CALCULATE (",
              "            [Costs (inc Fee)],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        ),",
              "\t\t// Partial month selected.",
              "        CALCULATE (",
              "            [Costs (inc Fee)],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs PQ",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected.",
              "        CALCULATE (",
              "            [Costs (inc Fee)],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Costs (inc Fee)],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs PM",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected. ",
              "        CALCULATE (",
              "            [Costs (inc Fee)],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Costs (inc Fee)],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs PP (inc Fee)",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [Costs PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [Costs PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Costs PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Costs PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Costs PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs WOW",
            "expression": " [Costs (inc Fee)] - [Costs PW]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs WOW%",
            "expression": "0",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs YOY",
            "expression": "[Costs (inc Fee)] - [Costs PY]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs QOQ",
            "expression": "[Costs (inc Fee)] - [Costs PQ]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs MOM",
            "expression": "[Costs (inc Fee)] - [Costs PM]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs YOY%",
            "expression": "DIVIDE ( [Costs YOY], [Costs PY] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs QOQ%",
            "expression": "DIVIDE ( [Costs QOQ], [Costs PQ] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs MOM%",
            "expression": "DIVIDE ( [Costs MOM], [Costs PM] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Order Value",
            "expression": [
              "",
              "ROUND (",
              "    IF (",
              "        HASONEVALUE ( Currencies[Currency Code] ),",
              "        SUMX (",
              "            CROSSJOIN ( Currencies, 'Calendar' ),",
              "            CALCULATE (",
              "                VALUES ( ExchangeRates[ExchangeRate] ) * SUM ( Transactions[SalesAmount] )",
              "            )",
              "        ),",
              "        SUM ( Transactions[SalesAmount] )",
              "    ),",
              "    2",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Sales PD",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[DayInEpoch] ),",
              "    CALCULATE (",
              "        [Sales],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[DayInEpoch] ),",
              "            'Calendar'[DayInEpoch]",
              "                = EARLIER ( 'Calendar'[DayInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Order Value PD",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[DayInEpoch] ),",
              "    CALCULATE (",
              "        [Order Value],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[DayInEpoch] ),",
              "            'Calendar'[DayInEpoch]",
              "                = EARLIER ( 'Calendar'[DayInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Commission PD",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[DayInEpoch] ),",
              "    CALCULATE (",
              "        [Commission],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[DayInEpoch] ),",
              "            'Calendar'[DayInEpoch]",
              "                = EARLIER ( 'Calendar'[DayInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "GP PD",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[DayInEpoch] ),",
              "    CALCULATE (",
              "        [GP],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[DayInEpoch] ),",
              "            'Calendar'[DayInEpoch]",
              "                = EARLIER ( 'Calendar'[DayInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "Costs PD",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[DayInEpoch] ),",
              "    CALCULATE (",
              "        [Costs (inc Fee)],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[DayInEpoch] ),",
              "            'Calendar'[DayInEpoch]",
              "                = EARLIER ( 'Calendar'[DayInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs POP (inc Fee)",
            "expression": "[Costs (inc Fee)] - [Costs PP (inc Fee)]",
            "formatString": "#,0.00",
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs POP% (inc Fee)",
            "expression": "DIVIDE([Costs POP (inc Fee)],[Costs PP (inc Fee)])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Sales PPD",
            "expression": [
              " 0",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Order Value PPD",
            "expression": "0",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "AOV PY",
            "expression": "DIVIDE([Order Value PY], [Sales PY])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV PQ",
            "expression": "DIVIDE([Order Value PQ], [Sales PQ])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV PM",
            "expression": "DIVIDE([Order Value PM], [Sales PM])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV PW",
            "expression": "DIVIDE([Order Value PW], [Sales PW])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV YOY",
            "expression": "[AOV] - [AOV PY]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV QOQ",
            "expression": "[AOV] - [AOV PQ]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV MOM",
            "expression": "[AOV] - [AOV PM]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV WOW",
            "expression": "[AOV] - [AOV PW]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV YOY%",
            "expression": "DIVIDE ( [AOV YOY], [AOV PY] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV QOQ%",
            "expression": "DIVIDE ( [AOV QOQ], [AOV PQ] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV MOM%",
            "expression": "DIVIDE ( [AOV MOM], [AOV PM] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV WOW%",
            "expression": "DIVIDE ( [AOV WOW], [AOV PW] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [AOV PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [AOV PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [AOV PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [AOV PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [AOV PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV POP",
            "expression": "[AOV] - [AOV PP]",
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "CTR PY",
            "description": "Click Through Rate Metrics",
            "expression": "DIVIDE([Clicks PY], [Impressions PY])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "AOV POP%",
            "expression": "DIVIDE([AOV POP],[AOV PP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "CTR PQ",
            "description": "Click Through Rate Metrics",
            "expression": "DIVIDE([Clicks PQ], [Impressions PQ])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR PM",
            "description": "Click Through Rate Metrics",
            "expression": "DIVIDE([Clicks PM], [Impressions PM])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR PW",
            "description": "Click Through Rate Metrics",
            "expression": "DIVIDE([Clicks PW], [Impressions PW])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR PP",
            "description": "Click Through Rate Metrics",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [CTR PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [CTR PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [CTR PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [CTR PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [CTR PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CR PY",
            "expression": "DIVIDE([Sales PY], [Clicks PY])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR PQ",
            "expression": "DIVIDE([Sales PQ], [Clicks PQ])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR PM",
            "expression": "DIVIDE([Sales PM], [Clicks PM])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR PW",
            "expression": "DIVIDE([Sales PW], [Clicks PW])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [CR PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [CR PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [CR PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [CR PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [CR PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "eCPS PY",
            "expression": "DIVIDE ( Transactions[Commission PY], Transactions[Sales PY] )",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS PQ",
            "expression": "DIVIDE ( Transactions[Commission PQ], Transactions[Sales PQ] )",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS PM",
            "expression": "DIVIDE ( Transactions[Commission PM], Transactions[Sales PM] )",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS PW",
            "expression": "DIVIDE ( Transactions[Commission PW], Transactions[Sales PW] )",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [eCPS PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [eCPS PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [eCPS PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [eCPS PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [eCPS PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "CTR YOY",
            "description": "Click Through Rate Metrics",
            "expression": "[CTR] - [CTR PY]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR QOQ",
            "description": "Click Through Rate Metrics",
            "expression": "[CTR] - [CTR PQ]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR MOM",
            "description": "Click Through Rate Metrics",
            "expression": "[CTR] - [CTR PM]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR WOW",
            "description": "Click Through Rate Metrics",
            "expression": "[CTR] - [CTR PW]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR YOY%",
            "description": "Click Through Rate Metrics",
            "expression": " [CTR] - [CTR PY]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR QOQ%",
            "description": "Click Through Rate Metrics",
            "expression": " [CTR] - [CTR PQ] ",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR MOM%",
            "description": "Click Through Rate Metrics",
            "expression": " [CTR]-[CTR PM] ",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR WOW%",
            "description": "Click Through Rate Metrics",
            "expression": "[CTR]- [CTR PW]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CR YOY",
            "expression": "[CR] - [CR PY]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate metrics"
          },
          {
            "name": "CR QOQ",
            "expression": "[CR] - [CR PQ]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate metrics"
          },
          {
            "name": "CR MOM",
            "expression": "[CR] - [CR PM]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate metrics"
          },
          {
            "name": "CR WOW",
            "expression": "[CR] - [CR PW]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate metrics"
          },
          {
            "name": "CR YOY%",
            "expression": "[CR YOY] -  [CR PY] ",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR QOQ%",
            "expression": "[CR QOQ] - [CR PQ] ",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR MOM%",
            "expression": "[CR MOM] -[CR PM] ",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR WOW%",
            "expression": " [CR WOW]- [CR PW] ",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "eCPS YOY",
            "expression": "[eCPS] - [eCPS PY]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS QOQ",
            "expression": "[eCPS] - [eCPS PQ]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS MOM",
            "expression": "[eCPS] - [eCPS PM]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS WOW",
            "expression": "[eCPS] - [eCPS PW]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS YOY%",
            "expression": "DIVIDE ( [eCPS YOY], [eCPS PY] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS QOQ%",
            "expression": "DIVIDE ( [eCPS QOQ], [eCPS PQ] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS MOM%",
            "expression": "DIVIDE ( [eCPS MOM], [eCPS PM] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS WOW%",
            "expression": "DIVIDE ( [eCPS WOW], [eCPS PW] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "Sales DOD",
            "expression": "[Sales] - [Sales PD]",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Sales DOD%",
            "expression": "DIVIDE ( [Sales DOD], [Sales PD] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "AOV PD",
            "expression": "DIVIDE([Order Value PD], [Sales PD])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "CR PD",
            "expression": "DIVIDE([Sales PD], [Clicks PD])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "eCPS PD",
            "expression": "DIVIDE ( Transactions[Commission PD], Transactions[Sales PD] )",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "CTR PD",
            "description": "Click Through Rate Metrics",
            "expression": "DIVIDE([Clicks PD], [Impressions PD])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "Order Value DOD",
            "expression": "[Order Value] - [Order Value PD]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Order Value DOD%",
            "expression": "DIVIDE ( [Order Value DOD], [Order Value PD] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Commission DOD",
            "expression": "[Commission] - [Commission PD]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "Commission DOD%",
            "expression": "DIVIDE ( [Commission DOD], [Commission PD] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Commission Metrics"
          },
          {
            "name": "GP DOD",
            "expression": "[GP] - [GP PD]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "GP DOD%",
            "expression": "DIVIDE ( [GP DOD], [GP PD] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Fee Metrics"
          },
          {
            "name": "Costs DOD",
            "expression": "[Costs (inc Fee)] - [Costs PD]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs DOD%",
            "expression": "DIVIDE ( [Costs DOD], [Costs PD] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "AOV DOD",
            "expression": "[AOV] - [AOV PD]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV DOD%",
            "expression": "DIVIDE ( [AOV DOD], [AOV PD] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "eCPS DOD",
            "expression": "[eCPS] - [eCPS PD]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "CR DOD",
            "expression": "[CR] - [CR PD]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate metrics"
          },
          {
            "name": "Commission PPD",
            "expression": " 0",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "GP PPD",
            "expression": "0",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Costs PPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [Costs (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs PPQ",
            "expression": [
              "",
              "CALCULATE (",
              "    [Costs (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs PPM",
            "expression": [
              "",
              "CALCULATE (",
              "    [Costs (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs PPD",
            "expression": " 0",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "Costs SPLY (inc Fee)",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [Costs PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Costs PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Costs PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Costs PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "COS (inc Fee)",
            "description": "Cost Of Sale",
            "expression": "DIVIDE([Costs (inc Fee)], [Order Value])",
            "formatString": "#,0.00",
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PY  (inc Fee)",
            "expression": "DIVIDE([Costs PY], [Order Value PY])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PQ  (inc Fee)",
            "expression": "DIVIDE([Costs PQ], [Order Value PQ])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PM  (inc Fee)",
            "expression": "DIVIDE([Costs PM], [Order Value PM])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PW  (inc Fee)",
            "expression": "DIVIDE([Costs PW], [Order Value PW])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PP  (inc Fee)",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [COS PD  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[Month] ), [COS PM  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [COS PQ  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[Year] ), [COS PY  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [COS PW  (inc Fee)],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS YOY  (inc Fee)",
            "expression": "[COS (inc Fee)] - [COS PY  (inc Fee)]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS QOQ  (inc Fee)",
            "expression": "[COS (inc Fee)] - [COS PQ  (inc Fee)]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS MOM  (inc Fee)",
            "expression": "[COS (inc Fee)] - [COS PM  (inc Fee)]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS WOW  (inc Fee)",
            "expression": "[COS (inc Fee)] - [COS PW  (inc Fee)]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS YOY%  (inc Fee)",
            "expression": "DIVIDE ( [COS YOY  (inc Fee)], [COS PY  (inc Fee)] )",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS QOQ%  (inc Fee)",
            "expression": "DIVIDE ( [COS QOQ  (inc Fee)], [COS PQ  (inc Fee)] )",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS MOM%  (inc Fee)",
            "expression": "DIVIDE ( [COS MOM  (inc Fee)], [COS PM  (inc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS WOW%  (inc Fee)",
            "expression": "DIVIDE ( [COS WOW  (inc Fee)], [COS PW  (inc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "ROI PY (inc Fee)",
            "expression": "DIVIDE([Order Value PY] , [Costs PY])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PQ  (inc Fee)",
            "expression": "DIVIDE([Order Value PQ] , [Costs PQ])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PM  (inc Fee)",
            "expression": "DIVIDE([Order Value PM] , [Costs PM])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PW (inc Fee)",
            "expression": "DIVIDE([Order Value PW] , [Costs PW])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PP  (inc Fee)",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [ROI PD (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[Month] ), [ROI PM  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [ROI PQ  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[Year] ), [ROI PY (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [ROI PW (inc Fee)],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI YOY  (inc Fee)",
            "expression": "DIVIDE([ROI (inc Fee)] , [ROI PY (inc Fee)])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI QOQ  (inc Fee)",
            "expression": "DIVIDE([ROI (inc Fee)] , [ROI PQ  (inc Fee)])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI MOM  (inc Fee)",
            "expression": "DIVIDE([ROI (inc Fee)] ,[ROI PM  (inc Fee)])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI WOW  (inc Fee)",
            "expression": "DIVIDE([ROI (inc Fee)] ,[ROI PW (inc Fee)])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI YOY%  (inc Fee)",
            "expression": "DIVIDE ( [ROI YOY  (inc Fee)], [ROI PY (inc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI QOQ%  (inc Fee)",
            "expression": "DIVIDE ( [ROI QOQ  (inc Fee)], [ROI PQ  (inc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI MOM%  (inc Fee)",
            "expression": "DIVIDE ( [ROI MOM  (inc Fee)], [ROI PM  (inc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI WOW%  (inc Fee)",
            "expression": "DIVIDE ( [ROI WOW  (inc Fee)], [ROI PW (inc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI POP  (inc Fee)",
            "expression": "[ROI (inc Fee)] - [ROI PP  (inc Fee)]",
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI POP%  (inc Fee)",
            "expression": "DIVIDE([ROI POP  (inc Fee)],[ROI PP  (inc Fee)])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PD (inc Fee)",
            "expression": "DIVIDE([Order Value PD] ,[Costs PD])",
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "COS PD  (inc Fee)",
            "expression": "DIVIDE([Costs PD], [Order Value PD])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "ROI DOD  (inc Fee)",
            "expression": "DIVIDE([ROI (inc Fee)] , [ROI PD (inc Fee)])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI DOD%  (inc Fee)",
            "expression": "DIVIDE ( [ROI DOD  (inc Fee)], [ROI PD (inc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "COS POP  (inc Fee)",
            "expression": "[COS (inc Fee)] - [COS PP  (inc Fee)]",
            "formatString": "#,0.00",
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS POP%  (inc Fee)",
            "expression": "DIVIDE([COS POP  (inc Fee)],[COS PP  (inc Fee)])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS DOD  (inc Fee)",
            "expression": "[COS (inc Fee)] - [COS PD  (inc Fee)]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "CTR POP",
            "expression": "[CTR] - [CTR PP]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR DOD",
            "expression": "[CTR] - [CTR PD]",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CPA",
            "expression": " DIVIDE([Commission] ,[Order Value])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA PD",
            "expression": " DIVIDE([Commission PD] ,[Order Value PD]) ",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA PW",
            "expression": " DIVIDE([Commission PW] ,[Order Value PW])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA PM",
            "expression": " DIVIDE([Commission PM] ,[Order Value PM])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA PQ",
            "expression": " DIVIDE([Commission PQ] ,[Order Value PQ])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA PY",
            "expression": " DIVIDE([Commission PY] ,[Order Value PY])",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [CPA PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [CPA PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [CPA PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [CPA PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [CPA PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA POP%",
            "expression": " DIVIDE([Commission PP] ,[Order Value PP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA DOD%",
            "expression": "  [CPA]- [CPA PD]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA WOW%",
            "expression": "  [CPA]- [CPA PW]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA MOM%",
            "expression": "  [CPA]- [CPA PM]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA QOQ%",
            "expression": "  [CPA]- [CPA PQ]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA YOY%",
            "expression": "  [CPA]- [CPA PY]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CTR POP%",
            "expression": " DIVIDE([Clicks PP], [Impressions PP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR DOD%",
            "expression": "[CTR] - [CTR PD]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CR POP%",
            "expression": "DIVIDE([Sales PP], [Clicks PP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR DOD%",
            "expression": "[CR] - [CR PD]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "AOV PPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [AOV],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV PPQ",
            "expression": [
              "",
              "CALCULATE (",
              "    [AOV],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV PPM",
            "expression": [
              "",
              "CALCULATE (",
              "    [AOV],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV PPD",
            "expression": " 0",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "Sales PPW",
            "expression": [
              "",
              "CALCULATE (",
              "    [Sales],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Sale Metrics"
          },
          {
            "name": "Order Value PPW",
            "expression": [
              "",
              "CALCULATE (",
              "    [Order Value],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "Commission PPW",
            "expression": [
              "",
              "CALCULATE (",
              "    [Commission],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "GP PPW",
            "expression": [
              "",
              "CALCULATE (",
              "    [GP],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "Costs PPW",
            "expression": [
              "",
              "CALCULATE (",
              "    [Costs (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "AOV PPW",
            "expression": [
              "",
              "CALCULATE (",
              "    [AOV],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "AOV SPLY",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [AOV PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [AOV PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [AOV PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [AOV PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PY (exc Fee)",
            "expression": "DIVIDE([Order Value PY] , [Commission PY])",
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "ROI PQ (exc Fee)",
            "expression": "DIVIDE([Order Value PQ] , [Commission PQ])",
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "ROI PM (exc Fee)",
            "expression": "DIVIDE([Order Value PM] ,[Commission PM])",
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "ROI PD (exc Fee)",
            "expression": "DIVIDE([Order Value PD] , [Commission PD])",
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "ROI PW (exc Fee)",
            "expression": "DIVIDE([Order Value PW] , [Commission PW])",
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "ROI PP (exc Fee)",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [ROI PD (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[Month] ), [ROI PM (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [ROI PQ (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[Year] ), [ROI PY (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [ROI PW (exc Fee)],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI YOY (exc Fee)",
            "expression": "DIVIDE([ROI (exc Fee)] , [ROI PY (exc Fee)])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI QOQ (exc Fee)",
            "expression": "DIVIDE([ROI (exc Fee)] , [ROI PQ (exc Fee)])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI MOM (exc Fee)",
            "expression": "DIVIDE([ROI (exc Fee)] ,[ROI PM (exc Fee)])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI DOD (exc Fee)",
            "expression": "DIVIDE([ROI (exc Fee)] , [ROI PD (exc Fee)])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI WOW (exc Fee)",
            "expression": "DIVIDE([ROI (exc Fee)] , [ROI PW (exc Fee)])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI YOY% (exc Fee)",
            "expression": "DIVIDE ( [ROI YOY (exc Fee)], [ROI PY (exc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI QOQ% (exc Fee)",
            "expression": "DIVIDE ( [ROI QOQ (exc Fee)], [ROI PQ (exc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI MOM% (exc Fee)",
            "expression": "DIVIDE ( [ROI MOM (exc Fee)], [ROI PM (exc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI DOD% (exc Fee)",
            "expression": "DIVIDE ( [ROI DOD (exc Fee)], [ROI PD (exc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI WOW% (exc Fee)",
            "expression": "DIVIDE ( [ROI WOW (exc Fee)], [ROI PW (exc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI POP (exc Fee)",
            "expression": "[ROI (exc Fee)] - [ROI PP (exc Fee)]",
            "formatString": "#,0.00",
            "displayFolder": "Order Value metrics"
          },
          {
            "name": "ROI POP% (exc Fee)",
            "expression": "DIVIDE([ROI POP (exc Fee)],[ROI PP (exc Fee)])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PPY  (inc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [ROI (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PPQ  (inc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [ROI (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PPM  (inc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [ROI (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")",
              "",
              "",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PPD  (inc Fee)",
            "expression": " 0",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PPW  (inc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [ROI (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI SPLY  (inc Fee)",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [ROI PPM  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [ROI PPQ  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[Year] ), [ROI PPY  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [ROI PPW  (inc Fee)],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PPY (exc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [ROI (exc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PPQ (exc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [ROI (exc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PPM (exc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [ROI (exc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PPD (exc Fee)",
            "expression": " 0",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI PPW (exc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [ROI (exc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI SPLY (exc Fee)",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [ROI PPM (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [ROI PPQ (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[Year] ), [ROI PPY (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [ROI PPW (exc Fee)],",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "ROI (exc Fee)",
            "expression": [
              "",
              "DIVIDE([Order Value] , [Commission])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          },
          {
            "name": "COS DOD%  (inc Fee)",
            "expression": "DIVIDE ( [COS DOD  (inc Fee)], [COS PD  (inc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true
          },
          {
            "name": "COS PPY  (inc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [COS (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "COS PPQ  (inc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [COS (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "COS PPM  (inc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [COS (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "COS PPD  (inc Fee)",
            "expression": " 0",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "COS PPW  (inc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [COS (inc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "COS SPLY  (inc Fee)",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [COS PPM  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [COS PPQ  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[Year] ), [COS PPY  (inc Fee)],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [COS PPW  (inc Fee)],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS (exc Fee)",
            "expression": "DIVIDE([Commission], [Order Value])",
            "formatString": "#,0.00",
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PY (exc Fee)",
            "expression": "DIVIDE([Commission PY], [Order Value PY])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PQ (exc Fee)",
            "expression": "DIVIDE([Commission PQ], [Order Value PQ])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PM (exc Fee)",
            "expression": "DIVIDE([Commission PM], [Order Value PM])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PD (exc Fee)",
            "expression": "DIVIDE([Commission PD], [Order Value PD])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PW (exc Fee)",
            "expression": "DIVIDE([Commission PW], [Order Value PW])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PP (exc Fee)",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [COS PD (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[Month] ), [COS PM (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [COS PQ (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[Year] ), [COS PY (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [COS PW (exc Fee)],",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS YOY (exc Fee)",
            "expression": "[COS (exc Fee)] - [COS PY (exc Fee)]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS QOQ (exc Fee)",
            "expression": "[COS (exc Fee)] - [COS PQ (exc Fee)]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS MOM (exc Fee)",
            "expression": "[COS (exc Fee)] - [COS PM (exc Fee)]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS DOD (exc Fee)",
            "expression": "[COS (exc Fee)] - [COS PD (exc Fee)]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS WOW (exc Fee)",
            "expression": "[COS (exc Fee)] - [COS PW (exc Fee)]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS YOY% (exc Fee)",
            "expression": "DIVIDE ( [COS YOY (exc Fee)], [COS PY (exc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS QOQ% (exc Fee)",
            "expression": "DIVIDE ( [COS QOQ (exc Fee)], [COS PQ (exc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS MOM% (exc Fee)",
            "expression": "DIVIDE ( [COS MOM (exc Fee)], [COS PM (exc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS DOD% (exc Fee)",
            "expression": "DIVIDE ( [COS DOD (exc Fee)], [COS PD (exc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS WOW% (exc Fee)",
            "expression": "DIVIDE ( [COS WOW (exc Fee)], [COS PW (exc Fee)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS POP (exc Fee)",
            "expression": "[COS (exc Fee)] - [COS PP (exc Fee)]",
            "formatString": "#,0.00",
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS POP% (exc Fee)",
            "expression": "DIVIDE([COS POP (exc Fee)],[COS PP (exc Fee)])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "eCPS DOD%",
            "expression": "DIVIDE ( [eCPS DOD], [eCPS PD] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "COS PPY (exc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [COS (exc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PPQ (exc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [COS (exc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PPM (exc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [COS (exc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PPD (exc Fee)",
            "expression": " 0",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS PPW (exc Fee)",
            "expression": [
              "",
              "CALCULATE (",
              "    [COS (exc Fee)],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "COS SPLY (exc Fee)",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [COS PPM (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [COS PPQ (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[Year] ), [COS PPY (exc Fee)],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [COS PPW (exc Fee)],",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "Cost of Sales Metrics"
          },
          {
            "name": "CR PPY",
            "description": "Conversion Rate metrics",
            "expression": "DIVIDE([Sales PPY], [Clicks PPY])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR PPQ",
            "description": "Conversion Rate metrics",
            "expression": "DIVIDE([Sales PPQ], [Clicks PPQ])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR PPM",
            "description": "Conversion Rate metrics",
            "expression": "DIVIDE([Sales PPM], [Clicks PPM])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR PPD",
            "description": "Conversion Rate metrics",
            "expression": "DIVIDE([Sales PPD], [Clicks PPD])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR PPW",
            "description": "Conversion Rate metrics",
            "expression": "DIVIDE([Sales PPW], [Clicks PPW])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CR SPLY",
            "description": "Conversion Rate metrics",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [CR PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [CR PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [CR PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [CR PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Conversion Rate Metrics"
          },
          {
            "name": "CPA PPY",
            "expression": " DIVIDE([Commission PPY] ,[Order Value PPY])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA PPQ",
            "expression": " DIVIDE([Commission PPQ] ,[Order Value PPQ])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA PPM",
            "expression": " DIVIDE([Commission PPM] ,[Order Value PPM])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA PPD",
            "expression": " DIVIDE([Commission PPD] ,[Order Value PPD])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA PPW",
            "expression": " DIVIDE([Commission PPW] ,[Order Value PPW])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CPA SPLY",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [CPA PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [CPA PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [CPA PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [CPA PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "CTR PPY",
            "expression": " DIVIDE([Clicks PPY], [Impressions PPY])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR PPQ",
            "expression": " DIVIDE([Clicks PPQ], [Impressions PPQ])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR PPM",
            "expression": " DIVIDE([Clicks PPM], [Impressions PPM])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR PPD",
            "expression": " DIVIDE([Clicks PPD], [Impressions PPD])",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "CTR PPW",
            "expression": " DIVIDE([Clicks PPW], [Impressions PPW])",
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "CTR SPLY",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [CTR PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [CTR PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [CTR PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [CTR PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Click Through Rate Metrics"
          },
          {
            "name": "eCPS POP",
            "expression": "[eCPS] - [eCPS PP]",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "eCPS POP%",
            "expression": " DIVIDE([eCPS], [eCPS PP])",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isHidden": true,
            "displayFolder": "Estimated Cost Per Sale"
          },
          {
            "name": "Costs (inc Fee)",
            "description": "Cost Per Action",
            "expression": [
              "",
              " ( [Commission] + [GP] )"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Cost Metrics"
          },
          {
            "name": "ROI (inc Fee)",
            "description": "Return On Investment",
            "expression": [
              "",
              "DIVIDE([Order Value] , [Costs (inc Fee)])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Order Value Metrics"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[Transactions].* FROM [ssas].[Transactions] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Transactions"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>CalendarKey</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdvertiserKey</string>",
              "      </key>",
              "      <value>",
              "        <int>98</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PublisherKey</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TransactionFlagKey</string>",
              "      </key>",
              "      <value>",
              "        <int>124</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TransactionCount</string>",
              "      </key>",
              "      <value>",
              "        <int>115</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>92</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CommissionAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FeeAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <int>80</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>LocationKey</string>",
              "      </key>",
              "      <value>",
              "        <int>88</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>InitiatingDeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SourceSystemKey</string>",
              "      </key>",
              "      <value>",
              "        <int>116</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>CalendarKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdvertiserKey</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PublisherKey</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TransactionFlagKey</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TransactionCount</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CommissionAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FeeAmount</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>LocationKey</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>InitiatingDeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SourceSystemKey</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>FeeAmount</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>LocationKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>InitiatingDeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SourceSystemKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Device",
        "columns": [
          {
            "name": "DeviceKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DeviceKey",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "Device",
            "dataType": "string",
            "sourceColumn": "Device",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Device Type",
            "dataType": "string",
            "sourceColumn": "Device Type"
          },
          {
            "name": "Device Group",
            "dataType": "string",
            "sourceColumn": "Device Group"
          }
        ],
        "partitions": [
          {
            "name": "Device",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[Devices].* FROM [ssas].[Devices] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>DeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>80</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Device Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>89</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Device</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>62</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Device Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>94</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>DeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Device Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Device</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Device Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Device Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Device Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[Devices].* FROM [ssas].[Devices] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Devices"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>DeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <int>80</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Device Type</string>",
              "      </key>",
              "      <value>",
              "        <int>89</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Device</string>",
              "      </key>",
              "      <value>",
              "        <int>62</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Device Group</string>",
              "      </key>",
              "      <value>",
              "        <int>94</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>DeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Device Type</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Device</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Device Group</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Device Type</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Device Group</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Impressions",
        "columns": [
          {
            "name": "CalendarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "AdvertiserKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AdvertiserKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "PublisherKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PublisherKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ImpressionCount",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ImpressionCount"
          },
          {
            "name": "SourceSystemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SourceSystemKey"
          }
        ],
        "partitions": [
          {
            "name": "ImpressionsByDate",
            "dataView": "full",
            "source": {
              "query": "SELECT  [ssas].[Impressions].* FROM [ssas].[Impressions]",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT  [ssas].[Impressions].* FROM [ssas].[Impressions]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Impressions",
            "expression": "SUM([ImpressionCount])",
            "formatString": "#,0"
          },
          {
            "name": "Impressions PY",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "\t\t// Full month selected.",
              "        CALCULATE (",
              "            [Impressions],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        ),",
              "\t\t// Partial month selected.",
              "        CALCULATE (",
              "            [Impressions],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 12",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions PQ",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected.",
              "        CALCULATE (",
              "            [Impressions],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Impressions],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 3",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions PM",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[YearMonthNumber] ),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Calendar'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Calendar'[MonthDays] ) ),",
              "        // Full month selected. ",
              "        CALCULATE (",
              "            [Impressions],",
              "            ALL ( 'Calendar' ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        ),",
              "        // Partial month selected. ",
              "        CALCULATE (",
              "            [Impressions],",
              "            ALL ( 'Calendar' ),",
              "            CALCULATETABLE ( VALUES ( 'Calendar'[MonthDayNumber] ) ),",
              "            FILTER (",
              "                ALL ( 'Calendar'[YearMonthNumber] ),",
              "                'Calendar'[YearMonthNumber]",
              "                    = EARLIER ( 'Calendar'[YearMonthNumber] ) - 1",
              "            )",
              "        )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions PW",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[WeekInEpoch] ),",
              "    CALCULATE (",
              "        [Impressions],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[WeekInEpoch] ),",
              "            'Calendar'[WeekInEpoch]",
              "                = EARLIER ( 'Calendar'[WeekInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions PD",
            "expression": [
              "",
              "SUMX (",
              "    VALUES ( 'Calendar'[DayInEpoch] ),",
              "    CALCULATE (",
              "        [Impressions],",
              "        ALL ( 'Calendar' ),",
              "        FILTER (",
              "            ALL ( 'Calendar'[DayInEpoch] ),",
              "            'Calendar'[DayInEpoch]",
              "                = EARLIER ( 'Calendar'[DayInEpoch] ) - 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions PP",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Date] ), [Impressions PD],",
              "    ISFILTERED ( 'Calendar'[Month] ), [Impressions PM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Impressions PQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Impressions PY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Impressions PW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Impressions POP",
            "expression": "[Impressions] - [Impressions PP]",
            "formatString": "#,0"
          },
          {
            "name": "Impressions POP%",
            "expression": "DIVIDE([Impressions POP],[Impressions PP])",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%"
          },
          {
            "name": "Impressions PPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [Impressions],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions PPQ",
            "expression": [
              "",
              "CALCULATE (",
              "    [Impressions],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[QuarterInYear] = MAX ( 'Calendar'[QuarterInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions PPM",
            "expression": [
              "",
              "CALCULATE (",
              "    [Impressions],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[YearNumber]",
              "            = MAX ( 'Calendar'[YearNumber] ) - 1",
              "            && 'Calendar'[MonthInYear] = MAX ( 'Calendar'[MonthInYear] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions PPW",
            "expression": [
              "",
              "CALCULATE (",
              "    [Impressions],",
              "    FILTER (",
              "        ALL ( Calendar ),",
              "        'Calendar'[ISOYearNumber]",
              "            = MAX ( 'Calendar'[ISOYearNumber] ) - 1",
              "            && 'Calendar'[ISOWeekNumber] = MAX ( 'Calendar'[ISOWeekNumber] )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions PPD",
            "expression": "0",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions SPLY",
            "expression": [
              "",
              "SWITCH (",
              "    TRUE,",
              "    ISFILTERED ( 'Calendar'[Month] ), [Impressions PPM],",
              "    ISFILTERED ( 'Calendar'[Quarter] ), [Impressions PPQ],",
              "    ISFILTERED ( 'Calendar'[Year] ), [Impressions PPY],",
              "    ISFILTERED ( 'Calendar'[ISO Week] ), [Impressions PPW],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Impressions YOY",
            "expression": " [Impressions] - [Impressions PY]",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions QOQ",
            "expression": " [Impressions] - [Impressions PQ]",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions MOM",
            "expression": " [Impressions] - [Impressions PM]",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions WOW",
            "expression": " [Impressions] - [Impressions PW]",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions YOY%",
            "expression": " DIVIDE ( [Impressions YOY], [Impressions PY] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true
          },
          {
            "name": "Impressions QOQ%",
            "expression": " DIVIDE ( [Impressions QOQ], [Impressions PQ] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true
          },
          {
            "name": "Impressions MOM%",
            "expression": " DIVIDE ( [Impressions MOM], [Impressions PM] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true
          },
          {
            "name": "Impressions WOW%",
            "expression": " DIVIDE ( [Impressions WOW], [Impressions PW] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true
          },
          {
            "name": "Impressions YTD",
            "expression": [
              "",
              "CALCULATE (",
              "    [Impressions],",
              "    FILTER (",
              "        ALL ( 'Calendar' ),",
              "        'Calendar'[YearNumber] = MAX ( 'Calendar'[YearNumber] )",
              "            && 'Calendar'[Date] <= MAX ( 'Calendar'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Impressions QTD",
            "expression": [
              "",
              "CALCULATE (",
              "    [Impressions],",
              "    FILTER (",
              "        ALL ( 'Calendar' ),",
              "        'Calendar'[YearQuarterNumber] = MAX ( 'Calendar'[YearQuarterNumber] )",
              "            && 'Calendar'[Date] <= MAX ( 'Calendar'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT  [ssas].[Impressions].* FROM [ssas].[Impressions]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "ImpressionsByDate"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "pbi"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT  [ssas].[Impressions].* FROM [ssas].[Impressions]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Locations",
        "columns": [
          {
            "name": "LocationKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LocationKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "sourceProviderType": "WChar",
            "dataCategory": "Country"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "sourceProviderType": "WChar",
            "dataCategory": "City"
          },
          {
            "name": "Latitude",
            "dataType": "double",
            "sourceColumn": "Latitude",
            "sourceProviderType": "Double",
            "dataCategory": "Latitude"
          },
          {
            "name": "Longitude",
            "dataType": "double",
            "sourceColumn": "Longitude",
            "sourceProviderType": "Double",
            "dataCategory": "Longitude"
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent",
            "dataCategory": "Continent"
          }
        ],
        "partitions": [
          {
            "name": "Locations",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[Locations].* FROM [ssas].[Locations] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>LocationKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>123</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Continent</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Country</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>City</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>66</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Latitude</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Longitude</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>109</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>LocationKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Continent</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Country</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>City</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Latitude</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Longitude</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Continent</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[Locations].* FROM [ssas].[Locations] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Locations"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>LocationKey</string>",
              "      </key>",
              "      <value>",
              "        <int>123</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Continent</string>",
              "      </key>",
              "      <value>",
              "        <int>107</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Country</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>City</string>",
              "      </key>",
              "      <value>",
              "        <int>66</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Latitude</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Longitude</string>",
              "      </key>",
              "      <value>",
              "        <int>109</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>LocationKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Continent</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Country</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>City</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Latitude</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Longitude</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Continent</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Currencies",
        "columns": [
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CurrencyKey",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Currency",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "Currency Code",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Currencies",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[Currencies].* FROM [ssas].[Currencies] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>CurrencyKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>92</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Currency</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Currency Code</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>102</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>CurrencyKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Currency</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Currency Code</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[Currencies].* FROM [ssas].[Currencies] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Currencies"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>CurrencyKey</string>",
              "      </key>",
              "      <value>",
              "        <int>92</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Currency</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Currency Code</string>",
              "      </key>",
              "      <value>",
              "        <int>102</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>CurrencyKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Currency</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Currency Code</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "ExchangeRates",
        "isHidden": true,
        "columns": [
          {
            "name": "CalendarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CurrencyKey",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "ExchangeRate",
            "dataType": "double",
            "sourceColumn": "ExchangeRate",
            "sourceProviderType": "Numeric"
          }
        ],
        "partitions": [
          {
            "name": "ExchangeRates",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[ExchangeRates].* FROM [ssas].[ExchangeRates] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CurrencyKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>92</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ExchangeRate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>100</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CurrencyKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ExchangeRate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[ExchangeRates].* FROM [ssas].[ExchangeRates] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "ExchangeRates"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>CalendarKey</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CurrencyKey</string>",
              "      </key>",
              "      <value>",
              "        <int>92</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ExchangeRate</string>",
              "      </key>",
              "      <value>",
              "        <int>100</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>CalendarKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CurrencyKey</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ExchangeRate</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Devices Initiating",
        "columns": [
          {
            "name": "InitiatingDeviceKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "InitiatingDeviceKey",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "Initiating Device Group",
            "dataType": "string",
            "sourceColumn": "Initiating Device Group",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Initiating Device Type",
            "dataType": "string",
            "sourceColumn": "Initiating Device Type",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Initiating Device",
            "dataType": "string",
            "sourceColumn": "Initiating Device",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "DevicesInitiating",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[DevicesInitiating].* FROM [ssas].[DevicesInitiating] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>InitiatingDeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Initiating Device Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>139</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Initiating Device Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>134</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Initiating Device</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>InitiatingDeviceKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Initiating Device Group</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Initiating Device Type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Initiating Device</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[DevicesInitiating].* FROM [ssas].[DevicesInitiating] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DevicesInitiating"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>InitiatingDeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Initiating Device Group</string>",
              "      </key>",
              "      <value>",
              "        <int>139</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Initiating Device Type</string>",
              "      </key>",
              "      <value>",
              "        <int>134</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Initiating Device</string>",
              "      </key>",
              "      <value>",
              "        <int>107</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>InitiatingDeviceKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Initiating Device Group</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Initiating Device Type</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Initiating Device</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Periods",
        "columns": [
          {
            "name": "CalendarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Period",
            "dataType": "string",
            "sourceColumn": "Period",
            "sortByColumn": "SortOrder",
            "sourceProviderType": "WChar"
          },
          {
            "name": "SortOrder",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SortOrder"
          }
        ],
        "partitions": [
          {
            "name": "Periods",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[Periods].* FROM [ssas].[Periods] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Period</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>60</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SortOrder</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>CalendarKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Period</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SortOrder</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>SortOrder</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[Periods].* FROM [ssas].[Periods] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Periods"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>CalendarKey</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Period</string>",
              "      </key>",
              "      <value>",
              "        <int>60</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SortOrder</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>CalendarKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Period</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SortOrder</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>SortOrder</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Sources",
        "columns": [
          {
            "name": "SourceSystemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SourceSystemKey",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "Source System",
            "dataType": "string",
            "sourceColumn": "Source System",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Sources",
            "dataView": "full",
            "source": {
              "query": " SELECT [ssas].[Sources].* FROM [ssas].[Sources] ",
              "dataSource": "Warehouse"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>SourceSystemKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>116</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Source System</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>SourceSystemKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Source System</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [ssas].[Sources].* FROM [ssas].[Sources] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sources"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "ssas"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>SourceSystemKey</string>",
              "      </key>",
              "      <value>",
              "        <int>116</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Source System</string>",
              "      </key>",
              "      <value>",
              "        <int>101</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>SourceSystemKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Source System</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "f3e7d1b6-b66d-442d-8958-0fe17cf59c03",
        "fromTable": "Transactions",
        "fromColumn": "CalendarKey",
        "toTable": "Calendar",
        "toColumn": "CalendarKey"
      },
      {
        "name": "2899db06-1417-4f45-bfb2-6f544c1ada7b",
        "fromTable": "Transactions",
        "fromColumn": "AdvertiserKey",
        "toTable": "Advertiser",
        "toColumn": "AdvertiserKey"
      },
      {
        "name": "5eb870ff-05a0-403d-865b-c995528a6278",
        "fromTable": "Transactions",
        "fromColumn": "PublisherKey",
        "toTable": "Publisher",
        "toColumn": "PublisherKey"
      },
      {
        "name": "7c4ae424-b503-40fb-9852-442cc78c4fea",
        "fromTable": "Transactions",
        "fromColumn": "TransactionFlagKey",
        "toTable": "Flags",
        "toColumn": "TransactionFlagKey"
      },
      {
        "name": "1a03a72e-bba4-473b-ac18-acd4f232b0a5",
        "fromTable": "Clicks",
        "fromColumn": "CalendarKey",
        "toTable": "Calendar",
        "toColumn": "CalendarKey"
      },
      {
        "name": "de4b3155-3a29-44d1-9cd5-7eb8c8a526f5",
        "fromTable": "Clicks",
        "fromColumn": "AdvertiserKey",
        "toTable": "Advertiser",
        "toColumn": "AdvertiserKey"
      },
      {
        "name": "ade2d84d-dd41-4525-9a99-9e3c953385c7",
        "fromTable": "Clicks",
        "fromColumn": "PublisherKey",
        "toTable": "Publisher",
        "toColumn": "PublisherKey"
      },
      {
        "name": "05410d9f-548c-452b-ad74-377de35f1762",
        "fromTable": "Transactions",
        "fromColumn": "DeviceKey",
        "toTable": "Device",
        "toColumn": "DeviceKey"
      },
      {
        "name": "3fa7ea82-65b1-4747-870f-0cdc18c120d3",
        "fromTable": "Impressions",
        "fromColumn": "CalendarKey",
        "toTable": "Calendar",
        "toColumn": "CalendarKey"
      },
      {
        "name": "6251a8d9-5bba-4e94-a312-bc33f1c7a22e",
        "fromTable": "Impressions",
        "fromColumn": "AdvertiserKey",
        "toTable": "Advertiser",
        "toColumn": "AdvertiserKey"
      },
      {
        "name": "21ef4dac-89d5-4c3d-9d53-998f120f6c9d",
        "fromTable": "Impressions",
        "fromColumn": "PublisherKey",
        "toTable": "Publisher",
        "toColumn": "PublisherKey"
      },
      {
        "name": "a12546ad-c5ce-4c99-9e4e-1867a93e6be4",
        "fromTable": "Transactions",
        "fromColumn": "LocationKey",
        "toTable": "Locations",
        "toColumn": "LocationKey"
      },
      {
        "name": "02c9bb5c-d9e2-4607-8ca5-9aa45e597f03",
        "fromTable": "ExchangeRates",
        "fromColumn": "CalendarKey",
        "toTable": "Calendar",
        "toColumn": "CalendarKey"
      },
      {
        "name": "871af31e-7e56-451a-962e-679710cd6f90",
        "fromTable": "ExchangeRates",
        "fromColumn": "CurrencyKey",
        "toTable": "Currencies",
        "toColumn": "CurrencyKey"
      },
      {
        "name": "76821b15-2484-4466-b134-03ffa51c5b18",
        "fromTable": "Clicks",
        "fromColumn": "DeviceKey",
        "toTable": "Device",
        "toColumn": "DeviceKey"
      },
      {
        "name": "101e5774-f919-4d30-998c-00cff724aaf6",
        "fromTable": "Transactions",
        "fromColumn": "InitiatingDeviceKey",
        "toTable": "Devices Initiating",
        "toColumn": "InitiatingDeviceKey"
      },
      {
        "name": "ae73615c-e844-411c-8cd5-f4900c7d6060",
        "fromTable": "Periods",
        "fromColumn": "CalendarKey",
        "toTable": "Calendar",
        "toColumn": "CalendarKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "2c2cff9d-8764-4268-9878-27c6a29253aa",
        "fromTable": "Clicks",
        "fromColumn": "SourceSystemKey",
        "toTable": "Sources",
        "toColumn": "SourceSystemKey"
      },
      {
        "name": "4bcbb35a-5214-445f-9dee-72ff596be128",
        "fromTable": "Impressions",
        "fromColumn": "SourceSystemKey",
        "toTable": "Sources",
        "toColumn": "SourceSystemKey"
      },
      {
        "name": "33a0ce72-d6ec-4081-97bb-cd459c05a070",
        "fromTable": "Transactions",
        "fromColumn": "SourceSystemKey",
        "toTable": "Sources",
        "toColumn": "SourceSystemKey"
      }
    ],
    "roles": [
      {
        "name": "Readers",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ZANOX-COM\\DWH_SSAS_Readers",
            "memberId": "S-1-5-21-4128844331-1145321147-3983486117-37322"
          }
        ]
      },
      {
        "name": "Administrators",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "ZANOX-COM\\DWH_AgentDEV",
            "memberId": "S-1-5-21-4128844331-1145321147-3983486117-37212"
          }
        ]
      }
    ]
  },
  "id": "SemanticModel"
}